# Generated by Django 5.0.14 on 2026-09-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdSenseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('publisher_id', models.CharField(blank=True, max_length=100)),
                ('home_slot', models.CharField(blank=True, max_length=100)),
                ('job_slot', models.CharField(blank=True, max_length=100)),
                ('content_slot', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AdSense settings',
                'verbose_name_plural': 'AdSense settings',
            },
        ),
    ]
