# Generated by Django 5.0.14 on 2026-09-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_dynamic_interview_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewcodeexample',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('javascript', 'Javascript'), ('c', 'C'), ('cpp', 'Cpp'), ('csharp', 'Csharp'), ('go', 'Go'), ('sql', 'Sql')], default='python', max_length=30),
        ),
    ]
