# Generated by Django 5.0.14 on 2026-09-13 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('work_mode', models.CharField(default='Hybrid', max_length=50)),
                ('job_type', models.CharField(default='Full Time', max_length=50)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('eligible_batch', models.CharField(blank=True, max_length=100)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('job_id', models.CharField(blank=True, max_length=100)),
                ('short_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('eligibility', models.TextField(blank=True)),
                ('required_skills', models.TextField(blank=True)),
                ('preferred_skills', models.TextField(blank=True)),
                ('selection_process', models.TextField(blank=True)),
                ('application_process', models.TextField(blank=True)),
                ('interview_preparation', models.TextField(blank=True)),
                ('fraud_alert', models.TextField(blank=True)),
                ('official_url', models.URLField(blank=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.company')),
            ],
            options={
                'ordering': ['-published_at', '-priority', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='jobs_job_slug_9562d1_idx'), models.Index(fields=['published_at'], name='jobs_job_publish_69cdb2_idx'), models.Index(fields=['deadline'], name='jobs_job_deadlin_c19edf_idx'), models.Index(fields=['is_published'], name='jobs_job_is_publ_6b90e5_idx'), models.Index(fields=['company'], name='jobs_job_company_9ee5ea_idx'), models.Index(fields=['location'], name='jobs_job_locatio_8b2f8c_idx'), models.Index(fields=['job_type'], name='jobs_job_job_typ_f6c220_idx'), models.Index(fields=['work_mode'], name='jobs_job_work_mo_424767_idx')],
            },
        ),
    ]
