import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { requestJson, uploadFile } from '../api/client'
import './admin.css'

const emptyJob = { company_name: '', title: '', location: '', work_mode: '', job_type: '', experience: '', qualification: '', eligible_batch: '', salary: '', job_id: '', short_description: '', description: '', responsibilities: '', eligibility: '', required_skills: '', preferred_skills: '', selection_process: '', application_process: '', interview_preparation: '', fraud_alert: '', official_url: '', deadline: '', seo_title: '', seo_description: '', is_published: true, is_featured: false, priority: 0 }
const jobFields = [['company_name', 'Company name'], ['title', 'Job title'], ['location', 'Location'], ['work_mode', 'Work mode'], ['job_type', 'Job type'], ['experience', 'Experience'], ['qualification', 'Qualification'], ['eligible_batch', 'Eligible batch'], ['salary', 'Salary / CTC'], ['job_id', 'Job ID'], ['responsibilities', 'Responsibilities'], ['eligibility', 'Eligibility'], ['required_skills', 'Required skills'], ['preferred_skills', 'Preferred skills'], ['selection_process', 'Selection process'], ['application_process', 'Application process'], ['interview_preparation', 'Interview preparation'], ['fraud_alert', 'Fraud alert']]
const emptyPdf = { title: '', description: '', content: '', category: 'Programming', tags: '', author: '', is_published: true, is_featured: false, pdf: null, thumbnail: null }
const emptyTopic = { name: '', description: '', icon: 'code', display_order: 0, is_published: true, seo_title: '', seo_description: '' }
const emptyQuestion = { topic_id: '', title: '', question: '', answer: '', explanation: '', example: '', key_points: '', problem_statement: '', input_format: '', output_format: '', constraints: '', tags: '', question_type: 'conceptual', difficulty: 'medium', display_order: 0, is_published: true, code_examples: [] }
const emptyAdsense = { enabled: false, publisher_id: '', home_slot: '', job_slot: '', content_slot: '', interview_slot: '' }

export default function AdminPage() {
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [loggedIn, setLoggedIn] = useState(Boolean(localStorage.getItem('skillbloom_access_token')))
  const [authorized, setAuthorized] = useState(false)
  const [authChecked, setAuthChecked] = useState(false)
  const [job, setJob] = useState(emptyJob)
  const [editingJobSlug, setEditingJobSlug] = useState('')
  const [pdf, setPdf] = useState(emptyPdf)
  const [topic, setTopic] = useState(emptyTopic)
  const [question, setQuestion] = useState(emptyQuestion)
  const [adsense, setAdsense] = useState(emptyAdsense)
  const [jobs, setJobs] = useState([])
  const [pdfResources, setPdfResources] = useState([])
  const [interviewTopics, setInterviewTopics] = useState([])
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')

  useEffect(() => {
    if (!localStorage.getItem('skillbloom_access_token')) { setAuthChecked(true); return }
    requestJson('/auth/me/').then((user) => { setAuthorized(Boolean(user.is_staff)); setLoggedIn(Boolean(user.is_staff)) }).catch(logout).finally(() => setAuthChecked(true))
  }, [])

  useEffect(() => {
    if (!authorized) return
    requestJson('/jobs/').then((data) => setJobs(data.results || data)).catch(() => setJobs([]))
    requestJson('/resources/').then((data) => setPdfResources(data.results || data)).catch(() => setPdfResources([]))
    requestJson('/interview/topics/').then((data) => setInterviewTopics(data.results || data)).catch(() => setInterviewTopics([]))
    requestJson('/core/adsense/').then(setAdsense).catch(() => {})
  }, [authorized, message])

  function logout() { localStorage.removeItem('skillbloom_access_token'); localStorage.removeItem('skillbloom_refresh_token'); setLoggedIn(false); setAuthorized(false) }
  function update(setter) { return (event) => { const { name, value, type, checked, files } = event.target; setter((current) => ({ ...current, [name]: type === 'checkbox' ? checked : type === 'file' ? files[0] : value })) } }
  function startEditJob(item) { setEditingJobSlug(item.slug); setJob({ ...emptyJob, ...item, company_name: item.company?.name || '', deadline: item.deadline ? item.deadline.slice(0, 16) : '' }); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  function resetJob() { setEditingJobSlug(''); setJob(emptyJob) }

  async function login(event) {
    event.preventDefault(); setError('')
    try { const data = await requestJson('/auth/login/', { method: 'POST', body: JSON.stringify({ email, password }) }); localStorage.setItem('skillbloom_access_token', data.access); if (data.refresh) localStorage.setItem('skillbloom_refresh_token', data.refresh); const user = await requestJson('/auth/me/'); if (!user.is_staff) throw new Error('This account is not authorized to access the admin panel.'); setAuthorized(true); setLoggedIn(true) } catch (loginError) { setError(loginError.message || 'Login failed.') }
  }

  async function saveJob(event) {
    event.preventDefault(); setError('')
    try { const endpoint = editingJobSlug ? `/jobs/manage/${editingJobSlug}/` : '/jobs/create/'; const method = editingJobSlug ? 'PATCH' : 'POST'; await requestJson(endpoint, { method, body: JSON.stringify({ ...job, priority: Number(job.priority) || 0, deadline: job.deadline || null }) }); const wasEditing = Boolean(editingJobSlug); resetJob(); setMessage(wasEditing ? 'Job updated successfully.' : 'Job published successfully.') } catch (saveError) { setError(saveError.message || 'Could not save this job.') }
  }

  async function deleteJob(slug) { if (!window.confirm('Delete this job permanently?')) return; try { await requestJson(`/jobs/delete/${slug}/`, { method: 'DELETE' }); setJobs((current) => current.filter((item) => item.slug !== slug)); setMessage('Job deleted successfully.') } catch (deleteError) { setError(deleteError.message || 'Could not delete this job.') } }
  async function uploadPdf(event) { event.preventDefault(); const formData = new FormData(); Object.entries(pdf).forEach(([key, value]) => { if (value !== null && value !== '') formData.append(key, value) }); try { await uploadFile('/resources/create/', formData); setPdf(emptyPdf); event.target.reset(); setMessage('Learning PDF uploaded successfully.') } catch (uploadError) { setError(uploadError.message || 'Could not upload this PDF.') } }
  async function deletePdf(slug) { if (!window.confirm('Delete this learning PDF permanently?')) return; try { await requestJson(`/resources/delete/${slug}/`, { method: 'DELETE' }); setPdfResources((current) => current.filter((item) => item.slug !== slug)); setMessage('Learning PDF deleted successfully.') } catch (deleteError) { setError(deleteError.message || 'Could not delete this PDF.') } }
  async function publishTopic(event) { event.preventDefault(); try { const created = await requestJson('/interview/topics/create/', { method: 'POST', body: JSON.stringify(topic) }); setInterviewTopics((current) => [...current, created]); setTopic(emptyTopic); setMessage('Interview topic published successfully.') } catch (saveError) { setError(saveError.message || 'Could not publish this topic.') } }
  async function publishQuestion(event) { event.preventDefault(); try { const created = await requestJson('/interview/create/', { method: 'POST', body: JSON.stringify(question) }); setQuestion(emptyQuestion); setMessage(`Interview question “${created.title}” published successfully.`) } catch (saveError) { setError(saveError.message || 'Could not publish this question.') } }
  async function saveAdsense(event) { event.preventDefault(); try { await requestJson('/core/adsense/', { method: 'PATCH', body: JSON.stringify(adsense) }); setMessage('AdSense settings saved.') } catch (saveError) { setError(saveError.message || 'Could not save AdSense settings.') } }

  if (!authChecked) return <div className="admin-page admin-login"><div className="admin-login-card"><p>Checking admin access...</p></div></div>
  if (!loggedIn) return <div className="admin-page admin-login"><div className="admin-login-card"><p className="admin-kicker">SkillBloom workspace</p><h1>Admin sign in</h1><p>Use your Django staff account to publish from mobile or laptop.</p><form onSubmit={login}><label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} required /></label><button className="admin-submit" type="submit">Sign in</button></form>{error && <p className="admin-error">{error}</p>}</div></div>
  if (!authorized) return <div className="admin-page admin-login"><div className="admin-login-card"><p className="admin-kicker">Restricted area</p><h1>Access denied</h1><p>Only authorized staff can access this panel.</p></div></div>

  return <main className="admin-page"><div className="admin-shell"><header className="admin-header"><div><p className="admin-kicker">SkillBloom workspace</p><h1>Content studio</h1><p>Publish and manage jobs, PDFs, interview questions, and ads.</p></div><div className="admin-header-actions"><Link className="admin-explore-link" to="/admin-panel/explore">Explore CMS</Link><button className="admin-logout" type="button" onClick={logout}>Sign out</button></div></header>{message && <p className="admin-success">{message}</p>}{error && <p className="admin-error">{error}</p>}
    <form className="admin-form" onSubmit={saveJob}><section className="admin-section"><div className="admin-section-heading"><h2>{editingJobSlug ? 'Edit job' : 'New job'}</h2>{editingJobSlug && <button className="admin-logout" type="button" onClick={resetJob}>Cancel edit</button>}</div><div className="admin-grid">{jobFields.map(([name, label]) => <label key={name}>{label}<input name={name} value={job[name] || ''} onChange={update(setJob)} /></label>)}</div><label>Short description<textarea name="short_description" value={job.short_description} onChange={update(setJob)} rows="3" /></label><label>Full description<textarea name="description" value={job.description} onChange={update(setJob)} rows="8" /></label><div className="admin-grid"><label>Official company URL<input type="url" name="official_url" value={job.official_url} onChange={update(setJob)} /></label><label>Application deadline<input type="datetime-local" name="deadline" value={job.deadline} onChange={update(setJob)} /></label></div><label>SEO title<input name="seo_title" value={job.seo_title} onChange={update(setJob)} /></label><label>SEO description<textarea name="seo_description" value={job.seo_description} onChange={update(setJob)} rows="3" /></label><div className="admin-options"><label><input type="checkbox" name="is_published" checked={job.is_published} onChange={update(setJob)} /> Publish job</label><label><input type="checkbox" name="is_featured" checked={job.is_featured} onChange={update(setJob)} /> Feature job</label></div><button className="admin-submit" type="submit">{editingJobSlug ? 'Update job' : 'Publish job'}</button></section></form>
    <section className="admin-form admin-section"><h2>Manage published jobs</h2><div className="jobs-list-table">{jobs.length ? jobs.map((item) => <div className="job-row" key={item.id}><div><strong>{item.title || 'Untitled job'}</strong><p>{item.company?.name || 'SkillBloom'}{item.location ? ` • ${item.location}` : ''}</p></div><div className="job-row-actions"><button className="admin-logout" type="button" onClick={() => startEditJob(item)}>Edit job</button><button className="admin-delete" type="button" onClick={() => deleteJob(item.slug)}>Delete job</button></div></div>) : <p className="admin-help">No jobs published yet.</p>}</div></section>
    <form className="admin-form" onSubmit={uploadPdf}><section className="admin-section"><h2>Learning PDF</h2><div className="admin-grid"><label>Title<input name="title" value={pdf.title} onChange={update(setPdf)} required /></label><label>Category<input name="category" value={pdf.category} onChange={update(setPdf)} /></label></div><label>Description<textarea name="description" value={pdf.description} onChange={update(setPdf)} rows="3" /></label><label>Full course content<textarea name="content" value={pdf.content} onChange={update(setPdf)} rows="10" /></label><label>PDF file<input type="file" name="pdf" accept="application/pdf" onChange={update(setPdf)} required /></label><button className="admin-submit" type="submit">Upload PDF</button></section></form>
    <section className="admin-form admin-section"><h2>Manage learning PDFs</h2><div className="jobs-list-table">{pdfResources.map((item) => <div className="job-row" key={item.id}><div><strong>{item.title}</strong><p>{item.category}</p></div><button className="admin-delete" type="button" onClick={() => deletePdf(item.slug)}>Delete PDF</button></div>)}</div></section>
    <form className="admin-form" onSubmit={publishTopic}><section className="admin-section"><h2>Interview topic</h2><div className="admin-grid"><label>Topic name<input name="name" value={topic.name} onChange={update(setTopic)} required /></label><label>Display order<input name="display_order" type="number" value={topic.display_order} onChange={update(setTopic)} /></label></div><label>Description<textarea name="description" value={topic.description} onChange={update(setTopic)} rows="3" /></label><label><input type="checkbox" name="is_published" checked={topic.is_published} onChange={update(setTopic)} /> Publish topic</label><button className="admin-submit" type="submit">Publish topic</button></section></form>
    <form className="admin-form" onSubmit={publishQuestion}><section className="admin-section"><h2>Interview question</h2><div className="admin-grid"><label>Topic<select name="topic_id" value={question.topic_id} onChange={update(setQuestion)} required><option value="">Select topic</option>{interviewTopics.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Question type<select name="question_type" value={question.question_type} onChange={update(setQuestion)}><option value="conceptual">Conceptual</option><option value="coding">Coding</option><option value="technical">Technical</option></select></label></div><label>Title<input name="title" value={question.title} onChange={update(setQuestion)} required /></label><label>Question<textarea name="question" value={question.question} onChange={update(setQuestion)} rows="4" required /></label><label>Answer<textarea name="answer" value={question.answer} onChange={update(setQuestion)} rows="5" /></label><label>Explanation<textarea name="explanation" value={question.explanation} onChange={update(setQuestion)} rows="4" /></label><label><input type="checkbox" name="is_published" checked={question.is_published} onChange={update(setQuestion)} /> Publish question</label><button className="admin-submit" type="submit">Publish question</button></section></form>
    <form className="admin-form" onSubmit={saveAdsense}><section className="admin-section"><h2>AdSense</h2><label><input type="checkbox" name="enabled" checked={adsense.enabled} onChange={update(setAdsense)} /> Enable AdSense</label><div className="admin-grid"><label>Publisher ID<input name="publisher_id" value={adsense.publisher_id} onChange={update(setAdsense)} /></label><label>Home slot<input name="home_slot" value={adsense.home_slot} onChange={update(setAdsense)} /></label><label>Job slot<input name="job_slot" value={adsense.job_slot} onChange={update(setAdsense)} /></label><label>Content slot<input name="content_slot" value={adsense.content_slot} onChange={update(setAdsense)} /></label><label>Interview slot<input name="interview_slot" value={adsense.interview_slot} onChange={update(setAdsense)} /></label></div><button className="admin-submit" type="submit">Save AdSense</button></section></form>
  </div></main>
}
