# Generated by Django 5.0.14 on 2026-09-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AITechPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('post_type', models.CharField(choices=[('news', 'Latest AI News'), ('ai_update', 'AI Updates'), ('company', 'Company Updates'), ('fact', 'Interesting Facts'), ('tool', 'AI Tools'), ('developer', 'Developer News'), ('career', 'Career & Industry Trends'), ('explained', 'Technology Explained'), ('weekly', 'Weekly AI Roundup'), ('video', 'YouTube Videos')], default='news', max_length=30)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='ai_posts/')),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='ai_tech_ait_slug_09208f_idx'), models.Index(fields=['is_published'], name='ai_tech_ait_is_publ_f76f78_idx'), models.Index(fields=['post_type'], name='ai_tech_ait_post_ty_7d341f_idx'), models.Index(fields=['published_at'], name='ai_tech_ait_publish_be77ef_idx')],
            },
        ),
    ]
