# Generated by Django 5.0.14 on 2026-09-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('DSA', 'DSA'), ('Java', 'Java'), ('Python', 'Python'), ('SQL', 'SQL'), ('Web Development', 'Web Development'), ('AI/ML', 'AI/ML'), ('Aptitude', 'Aptitude'), ('Interview', 'Interview'), ('Placement', 'Placement'), ('Resume', 'Resume'), ('Company Preparation', 'Company Preparation'), ('Other', 'Other')], default='Other', max_length=40)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='pdf_thumbnails/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='resources_p_slug_001335_idx'), models.Index(fields=['category'], name='resources_p_categor_02793e_idx'), models.Index(fields=['is_published'], name='resources_p_is_publ_7f8baa_idx'), models.Index(fields=['published_at'], name='resources_p_publish_0e1bfc_idx')],
            },
        ),
    ]
